server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb+srv://capcutapk123:hXipLjJLjpbuueLl@inventoryproductcluster.2hbdko3.mongodb.net/?retryWrites=true&w=majority&appName=InventoryProductCluster
      database : product_inventory